"""create users and saved_items

Revision ID: 9a2d76c47977
Revises: 
Create Date: 2026-09-17 10:46:59.628015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '9a2d76c47977'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('saved_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_saved_items_user_id', 'saved_items', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE (2026-09-22): baris drop_index/drop_table utk tabel `items` yang
    # tadinya di sini SUDAH DIHAPUS. Itu bukan bagian sah evolusi skema kita --
    # autogenerate waktu itu membandingkan ke database Sydney yang masih
    # menyisakan tabel `items` dari project Supabase LAMA (lihat catatan di
    # knowledge-graph.md, konsep orm-migrations), jadi ikut ke-diff sebagai
    # "hapus". Ketahuan waktu migrasi ini dijalankan ke database yang BENAR-
    # BENAR kosong (migrasi ke Supabase Singapore, Fase 5) -- gagal dengan
    # `UndefinedObject: index "idx_items_created_at" does not exist`, karena
    # objek itu memang tidak pernah ada di instalasi baru manapun. Aman
    # dihapus dari file ini: mengedit ISI migrasi yang revision id-nya sudah
    # tercatat di database lama tidak menjalankannya ulang di sana -- Alembic
    # cuma mencocokkan revision id, bukan mendiff ulang isinya.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_saved_items_user_id', table_name='saved_items')
    op.drop_table('saved_items')
    op.drop_table('users')
    # ### end Alembic commands ###
