"""create users and saved_items

Revision ID: 9a2d76c47977
Revises: 
Create Date: 2026-09-17 10:46:59.628015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '9a2d76c47977'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('saved_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_saved_items_user_id', 'saved_items', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE (2026-09-22): the drop_index/drop_table lines for an `items` table
    # that used to be here HAVE BEEN REMOVED. They were never a legitimate part
    # of our schema history -- autogenerate compared against the old Sydney
    # database, which still held an `items` table from a PREVIOUS Supabase
    # project, so it diffed it as a "drop". Found when this migration ran
    # against a TRULY empty database (the move to Supabase Singapore) -- it
    # failed with `UndefinedObject: index "idx_items_created_at" does not
    # exist`, because that object never existed in any fresh install. Safe to
    # remove from this file: editing the CONTENT of a migration whose revision
    # id is already recorded in an existing database doesn't re-run it there --
    # Alembic only matches revision ids, it doesn't re-diff the content.
    # Lesson: autogenerate diffs against the database's CURRENT state, so
    # always review the generated file and generate against a clean database.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_saved_items_user_id', table_name='saved_items')
    op.drop_table('saved_items')
    op.drop_table('users')
    # ### end Alembic commands ###
